'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _default1

  '''<summary>
  '''LblResultado control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblResultado As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''GrdInscritos control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GrdInscritos As Global.System.Web.UI.WebControls.DataGrid

  '''<summary>
  '''LblId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblId As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TxtCrp control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCrp As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtCPF control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCPF As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RequiredFieldValidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''cvCPF control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cvCPF As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''TxtNomeCompleto control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtNomeCompleto As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RequiredFieldValidator2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtNomeCracha control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtNomeCracha As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RequiredFieldValidator3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtEmail As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RequiredFieldValidator4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegularExpressionValidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''TxtCidade control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCidade As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValCidade control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValCidade As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtResidencial control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtResidencial As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RequiredFieldValidator5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtComercial control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtComercial As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtCelular control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCelular As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtInstituicao control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtInstituicao As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RequiredFieldValidator7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator7 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''LblDeficiencia control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblDeficiencia As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblBaixaVisao control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblBaixaVisao As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblCegueira control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblCegueira As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblSurdez control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblSurdez As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblDeficienciaFisica control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblDeficienciaFisica As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblDeficienciaIntelectual control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblDeficienciaIntelectual As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblOutra control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblOutra As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblQualOutra control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblQualOutra As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblRecurso control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblRecurso As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblBraille control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblBraille As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblGuia control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblGuia As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblLibras control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblLibras As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblGuiaInter control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblGuiaInter As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblOutro control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblOutro As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblQualOutro control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblQualOutro As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblSenha control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblSenha As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblCongresso control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblCongresso As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ValSumAdministracao control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValSumAdministracao As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''GrdExportExcel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GrdExportExcel As Global.System.Web.UI.WebControls.DataGrid
End Class
