'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class faleconosco

  '''<summary>
  '''TxtNome control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtNome As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValNome control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValNome As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ValidatorCalloutExtender1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidatorCalloutExtender1 As Global.AjaxControlToolkit.ValidatorCalloutExtender

  '''<summary>
  '''TxtEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtEmail As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RevValEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RevValEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegExpValEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegExpValEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''ValidatorCalloutExtender2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidatorCalloutExtender2 As Global.AjaxControlToolkit.ValidatorCalloutExtender

  '''<summary>
  '''ValidatorCalloutExtender3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidatorCalloutExtender3 As Global.AjaxControlToolkit.ValidatorCalloutExtender

  '''<summary>
  '''TxtMsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtMsg As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValMensagem control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValMensagem As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ValidatorCalloutExtender4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidatorCalloutExtender4 As Global.AjaxControlToolkit.ValidatorCalloutExtender

  '''<summary>
  '''BtnEnviar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BtnEnviar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
End Class
