'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class inscricoes

  '''<summary>
  '''RdoBtnEncEstudante17 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RdoBtnEncEstudante17 As Global.System.Web.UI.WebControls.RadioButton

  '''<summary>
  '''RdoBtnEncProfessores17 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RdoBtnEncProfessores17 As Global.System.Web.UI.WebControls.RadioButton

  '''<summary>
  '''LblTexto control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblTexto As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblCpf control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblCpf As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''LblEstudante control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblEstudante As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''RequiredFieldValidator3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtCrp control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCrp As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtCPF control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCPF As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValCPF control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValCPF As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''cvCPF control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cvCPF As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''RequiredFieldValidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtNomeCompleto control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtNomeCompleto As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValNome control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValNome As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtEmail As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegExpValEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegExpValEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''TxtCidade control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCidade As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RvCidade control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RvCidade As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtResidencial control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtResidencial As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValResidencial control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValResidencial As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''TxtComercial control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtComercial As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtCelular control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCelular As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtInstituicao control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtInstituicao As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RequiredFieldValidator2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RdoBtnDeficienciaSim control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RdoBtnDeficienciaSim As Global.System.Web.UI.WebControls.RadioButton

  '''<summary>
  '''RdoBtnDeficienciaNao control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RdoBtnDeficienciaNao As Global.System.Web.UI.WebControls.RadioButton

  '''<summary>
  '''PnlDeficiencia control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PnlDeficiencia As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''ChkBaixaVisao control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkBaixaVisao As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkCegueira control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkCegueira As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkSurdez control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkSurdez As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkDeficienciaFisica control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkDeficienciaFisica As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkDeficienciaIntelectual control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkDeficienciaIntelectual As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkOutradeficiencia control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkOutradeficiencia As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''TxtQualDeficiencia control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtQualDeficiencia As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''PnlNecessidadeRecurso control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PnlNecessidadeRecurso As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''RdoBtnRecursoSim control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RdoBtnRecursoSim As Global.System.Web.UI.WebControls.RadioButton

  '''<summary>
  '''RdoBtnRecursoNao control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RdoBtnRecursoNao As Global.System.Web.UI.WebControls.RadioButton

  '''<summary>
  '''ChkBraille control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkBraille As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkGuia control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkGuia As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkLibras control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkLibras As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkGuiaInter control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkGuiaInter As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''ChkOutroRecurso control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ChkOutroRecurso As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''LblQual control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LblQual As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TxtQualAtendimento control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtQualAtendimento As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''BtnEnviar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BtnEnviar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
End Class
